### PR TITLE
Allow dot commands to be run without a file loaded

### LINKED ISSUE #90: allow `. <instruction>` without `load`
from comments of #70

> @insou22 I should point out the reason i found this is because I wanted to execute an instruction in interactive mode so used `.` without first loading a file, but got an error. So tried to get around the error by loading an empty file.
> So i guess something else to look at is using the `.` command without a file loaded. for quickly checking behavior.
> _Originally posted by @Dylan-Brotherston in https://github.com/insou22/mipsy/issues/70#issuecomment-938470395_

> The question is what is done during a `load` that is required to run instructions?
> If a `load` only populates `.data` and `.text` with user directives/instructions then there shouldn't be anything blocking this.
> But if `load` initialises memory segments and registers then it's a little harder as they would need to be accessable.
> _Originally posted by @Dylan-Brotherston in https://github.com/insou22/mipsy/issues/70#issuecomment-938714398_

### PR DESCRIPTION
**Pull request by joooooooooooooooooooooooooooooooooooosh**
fixes #90 
I decided not to initialize the stack, frame or global pointers but this is open to change.

### CODE REVIEW

**Review by Dylan-Brotherston — APPROVED** [review]

**Comment by SpanishPear** [comment]
Have you tested this change on mipsy Web? We use runtime a lot so just
making sure it doesn't all die...

**Comment by Dylan-Brotherston** [comment]
Prod mipsy web has not been rebuilt, as they didn't add any additional features to it.

**Comment by joooooooooooooooooooooooooooooooooooosh** [comment]
I'm not talking about prod mipsy_web, I just checked out to `main` and ran `trunk serve`

**Comment by SpanishPear** [comment]
@joooooooooooooooooooooooooooooooooooosh are you going to investigate the regression? 😳

**Comment by joooooooooooooooooooooooooooooooooooosh** [comment]
I don't think it's an issue? Building `mipsy_web` on `main` and running `trunk serve` results in a functioning `mipsy_web` instance afaict

**Comment by SpanishPear** [comment]
Huh I see, welp sounds good then! :D 🥳

**Pull request merged**
