### PR TITLE
Make the mipsy_web highlight color configurable but changing how mipsy_web handles colour overrides

### PR DESCRIPTION
**Pull request by Dylan-Brotherston**

### CODE REVIEW

**Comment by Dylan-Brotherston** [comment]
Fixes  #239

**Comment by Dylan-Brotherston** [comment]
Also fix #240 because we can

**Comment by Dylan-Brotherston** [comment]
As far as i can tell, the following elements still can't have their color changed:
"(unsaved file changes)" text 
image

hrefs
image

`$sp` and `$fp`
image

Settings close button (hover)
image

**Comment by abiramen** [comment]
is there a good argument as to why we specifically highlight $sp and $fp?

**Comment by Dylan-Brotherston** [comment]
The current location of `$sp` and `$fp` are colored in the data tab
image

**Comment by Dylan-Brotherston** [comment]
"(unsaved file changes)" text
hrefs
Settings close button (hover)

are now configurable

menu buttons are `svg`s and might be tricky.

**Comment by SpanishPear** [comment]
(finally) going to approve this - in an ideal world, we would be changing things on the yew side (and not have it sent through a layer of FFI).

But, mipsy-web's engineering is far from the ideal world at this point, so happy to go with this, and note it for if/when mipsy_web 2 evolves

**Review by SpanishPear — APPROVED** [review]

**Pull request merged**
